debug: false

kafka:
  bootstrap.servers: "polite-jackal-12673-us1-kafka.upstash.io:9092"
  security.protocol: "SASL_SSL"
  sasl.mechanism: "SCRAM-SHA-256"
  sasl.username: "cG9saXRlLWphY2thbC0xMjY3MyQNnZN8rQI5A8bKDdsXcpO99b3i1RfkADBfrPQ"
  sasl.password: "NjA3OGFjYjYtYjhjZS00NDJlLTg5YjMtNWU2NTEyMDk1ZmRi"
  #  ssl.ca.location: "/path/to/ca-cert"
  #  ssl.certificate.location: "/path/to/client-cert"
  #  ssl.key.location: "/path/to/client-key"
  client.id: "order-service"
  topic: "order.orders"
  producer:
    acks: "all"
    retries: 5
  consumer:
    group.id: "order-group"
    auto.offset.reset: "earliest"

mongo:
  uri: "mongodb://admin:Mongo3988@localhost:27017/"
  db: "order_db"
  collection: "orders"